# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          echo "files=${{steps.file_changes.outputs.files}}" >> $GITHUB_ENV
      - name: test2
        run: |
          echo "${{ env.files }}"
      - uses: actions/checkout@master
      - name: Zip Folder
        run: |
          zip -r release.zip . -x ".git/*" ".github/*"
          pwd release.zip
      - name: Upload Release
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://5fjj44q4xa.execute-api.us-east-1.amazonaws.com/dev'
          method: 'POST'
          files: '{"release": "/home/runner/work/python-lambda-layers/python-lambda-layers/release.zip"}'
          data: "{changes: ${{env.files}}}"
